import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Default title",
    template: "%s | CBA",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
    title: "Twitter Title",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <h1>Welcome to the Blog</h1>
        </header>
        {children} 
        <footer>
          <p>Copyright © 2023</p>
          <p>All rights reserved</p>
          </footer>
      </body>
    </html>
  );
}
