import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Page Title Over here",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <h1> Home Page</h1>
      <Link href="/blog">Go to blog</Link>
    </>
  );
}
